### ISSUE TITLE
Issues with MIT licensing

### ISSUE THREAD

**Issue by ubiratansoares** [fabiocarballo/android-resources-checker#25]
First of all, congrats for the good job on this tool. Looks quite great!

It's quite hard to say that, but it seems that your project is not compliant with MIT license at all.

The reason for that is simple : your project takes A LOT of inspiration from the open-source work I've been doing at @dotanuki-labs. Particularly it is easy to realise that when comparing this project with [bitrise-reports](https://github.com/dotanuki-labs/bitrise-reports)

I can list a few of them:

- Same project structure driven by Poetry + Makefile (including some targets using the same names)
- Same Github Actions Workflows (`main.yml` and `publish.yml`), incluing Job's names, Python versions, pipeline steps
- Very similar file structure (`entrypoint.py`, `reporting.py`, `app.py`, etc)
- Very similar file contents, as per [entrypoint.py](https://github.com/dotanuki-labs/bitrise-reports/blob/main/bitrise_reports/entrypoint.py#L21-L39
) (from `bitrise-reports`) and [entrypoint.py](https://github.com/fabiocarballo/android-resources-checker/blob/master/android_resources_checker/entrypoint.py#L45-L62
) (from this project)

Hell, even some lines of `README` look the same ... and this [__init__](https://github.com/fabiocarballo/android-resources-checker/blob/master/android_resources_checker/__init__.py) kinda makes crystal clear that inspiration maybe went too far ... 

Open-source is meant to be collaborative and inspirational, yes. For sure I have no issues with people forking, modifying and/or re-distributing my code. Most likely that proves I'm in a good track at all.

However, licensing is important. Attribution is important. [This article does a terrific job](https://www.patrick-wied.at/blog/how-to-correctly-use-code-you-didnt-write
) elaborating on that

```
I love inspiring other people to do awesome stuff based on some of my concepts and thoughts and 
I’m happy when I could help you with my code. So everybody is free to use my code, but now the 
important part, under the given license terms. You could also say “credit where credits needed”. 

Open source in the context of software does not mean you can copy the nice stuff and paste 
it into your project and tell everybody you did a nice job.
```

I can't recommend enough also checking these two extra resources to understand how MIT license works :

- [Choose a license](https://choosealicense.com/licenses/mit/) on MIT
- [Wikipedia](https://en.wikipedia.org/wiki/MIT_License#License_terms) on MIT

It's also worth to highlight that [deploys on Pypi ](https://pypi.org/project/android-resources-checker/)ship the source code exactly as it was written, which means that you've shipped snippets and/or entire pieces of code written by me without proper attribution while re-distributing.

All of that being said : I'd like to ask you to change your `LICENSE.md` and `README.md` files with the following notice

```
Copyright (c) 2021 Dotanuki Labs, Fabio Carballo

[rest of the license terms]
```

so your project becomes compliant with MIT and plays well with open-source. I won't bother about previous releases wrongly copyrighted if you gently commit with this suggestion and deploy a new version of this project, so users can get the proper copyrighted code when installing / updating this tool.

I'm assuming here this issue eventually comes from some lacking of experience with open-source from your end, and* that is totally fine.  Knowing you from our days working together at N26 I'm 100% sure you don't need such copy+pasta over other Engineer's work. 

Thanks in advance

**Comment by fabiocarballo** [comment]
> First of all, congrats for the good job on this tool. Looks quite great!

Thanks! :)

Regarding all your points, I can't do anything else than to just agree :)

After you released the bitrise-reports project, I thought it was really cool and then used it as a reference given that 1) I found it really simple to understand to a python newbie like me, 2) had a whole setup prepared with CI and publishing that I had no experience in Python. I just saw a great open-sourced tool, done in a simple way and wanted to use the most I could to try to reach my goal here.

With this said, I want to make clear that the error on the licensing didn't come from a bad place; I indeed did what I can see now as a terrible quick search about the subject, and understood all I had to do was to add the license. As you mentioned this comes from my lack of experience in open-source (which was 0 until this week).

**Finally,**  1) the due credit was given and now you can see **Dotanuki Labs** in both the `README.md` and the `LICENSE.md`; and 2) I also deleted from Pypi all the previous versions (before the `0.0.7` with the updates) so that no badly copyrighted code is going around.
 
I hope all is cleared, thanks for pointing out the mistake; I tried to be absolutely quick to amend it.

Happy easter 🐰

**Comment by fabiocarballo** [comment]
I will close this issue, as the concerns were addressed.
